// Code generated by go-swagger; DO NOT EDIT.

package yggdrasil

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/project-flotta/flotta-operator/models"
)

// GetControlMessageForDeviceOKCode is the HTTP code returned for type GetControlMessageForDeviceOK
const GetControlMessageForDeviceOKCode int = 200

/*GetControlMessageForDeviceOK Success

swagger:response getControlMessageForDeviceOK
*/
type GetControlMessageForDeviceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewGetControlMessageForDeviceOK creates GetControlMessageForDeviceOK with default headers values
func NewGetControlMessageForDeviceOK() *GetControlMessageForDeviceOK {

	return &GetControlMessageForDeviceOK{}
}

// WithPayload adds the payload to the get control message for device o k response
func (o *GetControlMessageForDeviceOK) WithPayload(payload *models.Message) *GetControlMessageForDeviceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get control message for device o k response
func (o *GetControlMessageForDeviceOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetControlMessageForDeviceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetControlMessageForDeviceUnauthorizedCode is the HTTP code returned for type GetControlMessageForDeviceUnauthorized
const GetControlMessageForDeviceUnauthorizedCode int = 401

/*GetControlMessageForDeviceUnauthorized Unauthorized

swagger:response getControlMessageForDeviceUnauthorized
*/
type GetControlMessageForDeviceUnauthorized struct {
}

// NewGetControlMessageForDeviceUnauthorized creates GetControlMessageForDeviceUnauthorized with default headers values
func NewGetControlMessageForDeviceUnauthorized() *GetControlMessageForDeviceUnauthorized {

	return &GetControlMessageForDeviceUnauthorized{}
}

// WriteResponse to the client
func (o *GetControlMessageForDeviceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetControlMessageForDeviceForbiddenCode is the HTTP code returned for type GetControlMessageForDeviceForbidden
const GetControlMessageForDeviceForbiddenCode int = 403

/*GetControlMessageForDeviceForbidden Forbidden

swagger:response getControlMessageForDeviceForbidden
*/
type GetControlMessageForDeviceForbidden struct {
}

// NewGetControlMessageForDeviceForbidden creates GetControlMessageForDeviceForbidden with default headers values
func NewGetControlMessageForDeviceForbidden() *GetControlMessageForDeviceForbidden {

	return &GetControlMessageForDeviceForbidden{}
}

// WriteResponse to the client
func (o *GetControlMessageForDeviceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetControlMessageForDeviceNotFoundCode is the HTTP code returned for type GetControlMessageForDeviceNotFound
const GetControlMessageForDeviceNotFoundCode int = 404

/*GetControlMessageForDeviceNotFound Error

swagger:response getControlMessageForDeviceNotFound
*/
type GetControlMessageForDeviceNotFound struct {
}

// NewGetControlMessageForDeviceNotFound creates GetControlMessageForDeviceNotFound with default headers values
func NewGetControlMessageForDeviceNotFound() *GetControlMessageForDeviceNotFound {

	return &GetControlMessageForDeviceNotFound{}
}

// WriteResponse to the client
func (o *GetControlMessageForDeviceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetControlMessageForDeviceInternalServerErrorCode is the HTTP code returned for type GetControlMessageForDeviceInternalServerError
const GetControlMessageForDeviceInternalServerErrorCode int = 500

/*GetControlMessageForDeviceInternalServerError Error

swagger:response getControlMessageForDeviceInternalServerError
*/
type GetControlMessageForDeviceInternalServerError struct {
}

// NewGetControlMessageForDeviceInternalServerError creates GetControlMessageForDeviceInternalServerError with default headers values
func NewGetControlMessageForDeviceInternalServerError() *GetControlMessageForDeviceInternalServerError {

	return &GetControlMessageForDeviceInternalServerError{}
}

// WriteResponse to the client
func (o *GetControlMessageForDeviceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
