// Code generated by go-swagger; DO NOT EDIT.

package yggdrasil

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDataMessageForDeviceParams creates a new GetDataMessageForDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDataMessageForDeviceParams() *GetDataMessageForDeviceParams {
	return &GetDataMessageForDeviceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataMessageForDeviceParamsWithTimeout creates a new GetDataMessageForDeviceParams object
// with the ability to set a timeout on a request.
func NewGetDataMessageForDeviceParamsWithTimeout(timeout time.Duration) *GetDataMessageForDeviceParams {
	return &GetDataMessageForDeviceParams{
		timeout: timeout,
	}
}

// NewGetDataMessageForDeviceParamsWithContext creates a new GetDataMessageForDeviceParams object
// with the ability to set a context for a request.
func NewGetDataMessageForDeviceParamsWithContext(ctx context.Context) *GetDataMessageForDeviceParams {
	return &GetDataMessageForDeviceParams{
		Context: ctx,
	}
}

// NewGetDataMessageForDeviceParamsWithHTTPClient creates a new GetDataMessageForDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDataMessageForDeviceParamsWithHTTPClient(client *http.Client) *GetDataMessageForDeviceParams {
	return &GetDataMessageForDeviceParams{
		HTTPClient: client,
	}
}

/* GetDataMessageForDeviceParams contains all the parameters to send to the API endpoint
   for the get data message for device operation.

   Typically these are written to a http.Request.
*/
type GetDataMessageForDeviceParams struct {

	/* DeviceID.

	   Device ID
	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get data message for device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataMessageForDeviceParams) WithDefaults() *GetDataMessageForDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get data message for device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataMessageForDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get data message for device params
func (o *GetDataMessageForDeviceParams) WithTimeout(timeout time.Duration) *GetDataMessageForDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data message for device params
func (o *GetDataMessageForDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data message for device params
func (o *GetDataMessageForDeviceParams) WithContext(ctx context.Context) *GetDataMessageForDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data message for device params
func (o *GetDataMessageForDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data message for device params
func (o *GetDataMessageForDeviceParams) WithHTTPClient(client *http.Client) *GetDataMessageForDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data message for device params
func (o *GetDataMessageForDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the get data message for device params
func (o *GetDataMessageForDeviceParams) WithDeviceID(deviceID string) *GetDataMessageForDeviceParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the get data message for device params
func (o *GetDataMessageForDeviceParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataMessageForDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
