# permissions for end users to edit edgeautoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgeautoconfig-editor-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeautoconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeautoconfigs/status
  verbs:
  - get
