# permissions for end users to view edgeautoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgeautoconfig-viewer-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeautoconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeautoconfigs/status
  verbs:
  - get
