// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FinalizeDeviceRegistrationHandlerFunc turns a function with the right signature into a finalize device registration handler
type FinalizeDeviceRegistrationHandlerFunc func(FinalizeDeviceRegistrationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FinalizeDeviceRegistrationHandlerFunc) Handle(params FinalizeDeviceRegistrationParams) middleware.Responder {
	return fn(params)
}

// FinalizeDeviceRegistrationHandler interface for that can handle valid finalize device registration params
type FinalizeDeviceRegistrationHandler interface {
	Handle(FinalizeDeviceRegistrationParams) middleware.Responder
}

// NewFinalizeDeviceRegistration creates a new http.Handler for the finalize device registration operation
func NewFinalizeDeviceRegistration(ctx *middleware.Context, handler FinalizeDeviceRegistrationHandler) *FinalizeDeviceRegistration {
	return &FinalizeDeviceRegistration{Context: ctx, Handler: handler}
}

/*FinalizeDeviceRegistration swagger:route PUT /namespaces/{namespace}/devices/{device-id}/register finalizeDeviceRegistration

Updates the status of the device as registered and its hardware configuration

*/
type FinalizeDeviceRegistration struct {
	Context *middleware.Context
	Handler FinalizeDeviceRegistrationHandler
}

func (o *FinalizeDeviceRegistration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFinalizeDeviceRegistrationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
