// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// FinalizeDeviceRegistrationURL generates an URL for the finalize device registration operation
type FinalizeDeviceRegistrationURL struct {
	DeviceID  string
	Namespace string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FinalizeDeviceRegistrationURL) WithBasePath(bp string) *FinalizeDeviceRegistrationURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FinalizeDeviceRegistrationURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *FinalizeDeviceRegistrationURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/namespaces/{namespace}/devices/{device-id}/register"

	deviceID := o.DeviceID
	if deviceID != "" {
		_path = strings.Replace(_path, "{device-id}", deviceID, -1)
	} else {
		return nil, errors.New("deviceId is required on FinalizeDeviceRegistrationURL")
	}

	namespace := o.Namespace
	if namespace != "" {
		_path = strings.Replace(_path, "{namespace}", namespace, -1)
	} else {
		return nil, errors.New("namespace is required on FinalizeDeviceRegistrationURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/flotta-backend/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *FinalizeDeviceRegistrationURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *FinalizeDeviceRegistrationURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *FinalizeDeviceRegistrationURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on FinalizeDeviceRegistrationURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on FinalizeDeviceRegistrationURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *FinalizeDeviceRegistrationURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
