// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/project-flotta/flotta-operator/models"
)

// NewInitializeDeviceRegistrationParams creates a new InitializeDeviceRegistrationParams object
// no default values defined in spec.
func NewInitializeDeviceRegistrationParams() InitializeDeviceRegistrationParams {

	return InitializeDeviceRegistrationParams{}
}

// InitializeDeviceRegistrationParams contains all the bound params for the initialize device registration operation
// typically these are obtained from a http.Request
//
// swagger:parameters InitializeDeviceRegistration
type InitializeDeviceRegistrationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Device ID
	  Required: true
	  In: path
	*/
	DeviceID string
	/*Namespace where the device resides
	  Required: true
	  In: path
	*/
	Namespace string
	/*
	  Required: true
	  In: body
	*/
	RegistrationInformation *models.DeviceRegistrationRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewInitializeDeviceRegistrationParams() beforehand.
func (o *InitializeDeviceRegistrationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDeviceID, rhkDeviceID, _ := route.Params.GetOK("device-id")
	if err := o.bindDeviceID(rDeviceID, rhkDeviceID, route.Formats); err != nil {
		res = append(res, err)
	}

	rNamespace, rhkNamespace, _ := route.Params.GetOK("namespace")
	if err := o.bindNamespace(rNamespace, rhkNamespace, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.DeviceRegistrationRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("registrationInformation", "body", ""))
			} else {
				res = append(res, errors.NewParseError("registrationInformation", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RegistrationInformation = &body
			}
		}
	} else {
		res = append(res, errors.Required("registrationInformation", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDeviceID binds and validates parameter DeviceID from path.
func (o *InitializeDeviceRegistrationParams) bindDeviceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.DeviceID = raw

	return nil
}

// bindNamespace binds and validates parameter Namespace from path.
func (o *InitializeDeviceRegistrationParams) bindNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Namespace = raw

	return nil
}
