// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/project-flotta/flotta-operator/models"
)

// InitializeDeviceRegistrationOKCode is the HTTP code returned for type InitializeDeviceRegistrationOK
const InitializeDeviceRegistrationOKCode int = 200

/*InitializeDeviceRegistrationOK Success

swagger:response initializeDeviceRegistrationOK
*/
type InitializeDeviceRegistrationOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeviceRegistrationResponse `json:"body,omitempty"`
}

// NewInitializeDeviceRegistrationOK creates InitializeDeviceRegistrationOK with default headers values
func NewInitializeDeviceRegistrationOK() *InitializeDeviceRegistrationOK {

	return &InitializeDeviceRegistrationOK{}
}

// WithPayload adds the payload to the initialize device registration o k response
func (o *InitializeDeviceRegistrationOK) WithPayload(payload *models.DeviceRegistrationResponse) *InitializeDeviceRegistrationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initialize device registration o k response
func (o *InitializeDeviceRegistrationOK) SetPayload(payload *models.DeviceRegistrationResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitializeDeviceRegistrationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InitializeDeviceRegistrationUnauthorizedCode is the HTTP code returned for type InitializeDeviceRegistrationUnauthorized
const InitializeDeviceRegistrationUnauthorizedCode int = 401

/*InitializeDeviceRegistrationUnauthorized Unauthorized

swagger:response initializeDeviceRegistrationUnauthorized
*/
type InitializeDeviceRegistrationUnauthorized struct {
}

// NewInitializeDeviceRegistrationUnauthorized creates InitializeDeviceRegistrationUnauthorized with default headers values
func NewInitializeDeviceRegistrationUnauthorized() *InitializeDeviceRegistrationUnauthorized {

	return &InitializeDeviceRegistrationUnauthorized{}
}

// WriteResponse to the client
func (o *InitializeDeviceRegistrationUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// InitializeDeviceRegistrationForbiddenCode is the HTTP code returned for type InitializeDeviceRegistrationForbidden
const InitializeDeviceRegistrationForbiddenCode int = 403

/*InitializeDeviceRegistrationForbidden Forbidden

swagger:response initializeDeviceRegistrationForbidden
*/
type InitializeDeviceRegistrationForbidden struct {
}

// NewInitializeDeviceRegistrationForbidden creates InitializeDeviceRegistrationForbidden with default headers values
func NewInitializeDeviceRegistrationForbidden() *InitializeDeviceRegistrationForbidden {

	return &InitializeDeviceRegistrationForbidden{}
}

// WriteResponse to the client
func (o *InitializeDeviceRegistrationForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

/*InitializeDeviceRegistrationDefault Error

swagger:response initializeDeviceRegistrationDefault
*/
type InitializeDeviceRegistrationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.DeviceRegistrationResponse `json:"body,omitempty"`
}

// NewInitializeDeviceRegistrationDefault creates InitializeDeviceRegistrationDefault with default headers values
func NewInitializeDeviceRegistrationDefault(code int) *InitializeDeviceRegistrationDefault {
	if code <= 0 {
		code = 500
	}

	return &InitializeDeviceRegistrationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the initialize device registration default response
func (o *InitializeDeviceRegistrationDefault) WithStatusCode(code int) *InitializeDeviceRegistrationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the initialize device registration default response
func (o *InitializeDeviceRegistrationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the initialize device registration default response
func (o *InitializeDeviceRegistrationDefault) WithPayload(payload *models.DeviceRegistrationResponse) *InitializeDeviceRegistrationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initialize device registration default response
func (o *InitializeDeviceRegistrationDefault) SetPayload(payload *models.DeviceRegistrationResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitializeDeviceRegistrationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
