// Code generated by go-swagger; DO NOT EDIT.

// Package restapi FlottaManagement
//
//	Flotta Edge Management
//	Schemes:
//	  https
//	Host: localhost
//	BasePath: /api/flotta-management/v1
//	Version: 1.0.0
//	License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: Flotta flotta<flotta@redhat.com> https://github.com/project-flotta
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
