// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Kube4EdgeManagement
//
//  Kube for Edge Management
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /api/k4e-management/v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
