// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Kube for Edge Management",
    "title": "Kube4EdgeManagement",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/api/k4e-management/v1",
  "paths": {
    "/device/register": {
      "post": {
        "security": [
          {
            "agentAuth": []
          }
        ],
        "tags": [
          "devices"
        ],
        "operationId": "RegisterDevice",
        "parameters": [
          {
            "description": "Device registration information",
            "name": "registration-info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/registration-info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "schema": {
              "$ref": "#/definitions/registration-confirmation"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Error"
          },
          "500": {
            "description": "Error"
          }
        }
      }
    },
    "/device/{device_id}": {
      "get": {
        "security": [
          {
            "agentAuth": []
          }
        ],
        "tags": [
          "devices"
        ],
        "operationId": "GetDeviceConfiguration",
        "parameters": [
          {
            "type": "string",
            "description": "Device to get configuration for",
            "name": "device_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/device-configuration"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Error"
          },
          "500": {
            "description": "Error"
          }
        }
      }
    }
  },
  "definitions": {
    "cpu": {
      "type": "object",
      "properties": {
        "architecture": {
          "type": "string"
        },
        "count": {
          "type": "integer"
        },
        "flags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "frequency": {
          "type": "number"
        },
        "model_name": {
          "type": "string"
        }
      }
    },
    "device-configuration": {
      "type": "object",
      "properties": {
        "device_id": {
          "description": "Device identifier",
          "type": "string"
        },
        "workloads": {
          "description": "List of workloads deployed to the device",
          "$ref": "#/definitions/workload-list"
        }
      }
    },
    "hardware-info": {
      "type": "object",
      "properties": {
        "cpu": {
          "$ref": "#/definitions/cpu"
        },
        "hostname": {
          "type": "string"
        },
        "memory": {
          "$ref": "#/definitions/memory"
        }
      }
    },
    "memory": {
      "type": "object",
      "properties": {
        "physical_bytes": {
          "type": "integer"
        },
        "usable_bytes": {
          "type": "integer"
        }
      }
    },
    "registration-confirmation": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      }
    },
    "registration-info": {
      "type": "object",
      "properties": {
        "hardware": {
          "description": "Hardware information",
          "$ref": "#/definitions/hardware-info"
        },
        "os_image_id": {
          "type": "string"
        }
      }
    },
    "workload": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the workload",
          "type": "string"
        }
      }
    },
    "workload-list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/workload"
      }
    }
  },
  "securityDefinitions": {
    "agentAuth": {
      "type": "apiKey",
      "name": "X-Secret-Key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Device management",
      "name": "devices"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Kube for Edge Management",
    "title": "Kube4EdgeManagement",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/api/k4e-management/v1",
  "paths": {
    "/device/register": {
      "post": {
        "security": [
          {
            "agentAuth": []
          }
        ],
        "tags": [
          "devices"
        ],
        "operationId": "RegisterDevice",
        "parameters": [
          {
            "description": "Device registration information",
            "name": "registration-info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/registration-info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "schema": {
              "$ref": "#/definitions/registration-confirmation"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Error"
          },
          "500": {
            "description": "Error"
          }
        }
      }
    },
    "/device/{device_id}": {
      "get": {
        "security": [
          {
            "agentAuth": []
          }
        ],
        "tags": [
          "devices"
        ],
        "operationId": "GetDeviceConfiguration",
        "parameters": [
          {
            "type": "string",
            "description": "Device to get configuration for",
            "name": "device_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/device-configuration"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Error"
          },
          "500": {
            "description": "Error"
          }
        }
      }
    }
  },
  "definitions": {
    "cpu": {
      "type": "object",
      "properties": {
        "architecture": {
          "type": "string"
        },
        "count": {
          "type": "integer"
        },
        "flags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "frequency": {
          "type": "number"
        },
        "model_name": {
          "type": "string"
        }
      }
    },
    "device-configuration": {
      "type": "object",
      "properties": {
        "device_id": {
          "description": "Device identifier",
          "type": "string"
        },
        "workloads": {
          "description": "List of workloads deployed to the device",
          "$ref": "#/definitions/workload-list"
        }
      }
    },
    "hardware-info": {
      "type": "object",
      "properties": {
        "cpu": {
          "$ref": "#/definitions/cpu"
        },
        "hostname": {
          "type": "string"
        },
        "memory": {
          "$ref": "#/definitions/memory"
        }
      }
    },
    "memory": {
      "type": "object",
      "properties": {
        "physical_bytes": {
          "type": "integer"
        },
        "usable_bytes": {
          "type": "integer"
        }
      }
    },
    "registration-confirmation": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      }
    },
    "registration-info": {
      "type": "object",
      "properties": {
        "hardware": {
          "description": "Hardware information",
          "$ref": "#/definitions/hardware-info"
        },
        "os_image_id": {
          "type": "string"
        }
      }
    },
    "workload": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the workload",
          "type": "string"
        }
      }
    },
    "workload-list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/workload"
      }
    }
  },
  "securityDefinitions": {
    "agentAuth": {
      "type": "apiKey",
      "name": "X-Secret-Key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Device management",
      "name": "devices"
    }
  ]
}`))
}
