@startuml
'https://plantuml.com/deployment-diagram

frame Kubernetes {
    node Operator {
      control "Flotta controller" as controller
      interface "http  API" as operatorAPI

    }
    file "EdgeWorkload CR" as workload
    file "EdgeDevice CR" as deviceCR
    database "Object Storage" as objectStore
}

node Device {
    component Agent
    control Podman
    collections Workloads
}
deviceCR o-- workload

Operator -[dashed]-> workload: process
Operator -[dashed]-> deviceCR: process
Operator -left-> objectStore: provision

Agent ---> operatorAPI: get desired state
Agent --> operatorAPI: update status
Agent --> Podman : CRUD/monitor workloads
Agent -> objectStore : upload files

Podman -[dashed]-> Workloads: supervise workloads


@enduml