@startuml

frame Kubernetes {
    component "Flotta Operator" as operator
    database "Object Bucket Claim" as buckets
    interface S3
}

frame "Edge Device" {
    node "Flotta Agent" as deviceAgent
}

buckets -down- S3: API
deviceAgent --> S3: Upload files
deviceAgent -up---> operator : Get configuration

operator -left-> buckets: Provision

@enduml