@startuml
'https://plantuml.com/sequence-diagram

title workload deployment
autonumber

actor User

User -> "EdgeWorkload CR": Create
Operator -> "EdgeWorkload CR": Process
Operator -> "EdgeDevice CR": add workload reference to status
Operator -> Agent: Send pod yaml
Operator -> "EdgeDevice CR": Set workload status to deploying
Agent -> nftables: open ports
Agent -> Podman: run pod

loop
Agent -> Operator: Heartbeat with workload information
Operator -> "EdgeWorkload CR": Update status
end


@enduml