// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jakub-dzon/k4e-operator/models"
)

// RegisterDeviceOKCode is the HTTP code returned for type RegisterDeviceOK
const RegisterDeviceOKCode int = 200

/*RegisterDeviceOK Success.

swagger:response registerDeviceOK
*/
type RegisterDeviceOK struct {

	/*
	  In: Body
	*/
	Payload *models.RegistrationConfirmation `json:"body,omitempty"`
}

// NewRegisterDeviceOK creates RegisterDeviceOK with default headers values
func NewRegisterDeviceOK() *RegisterDeviceOK {

	return &RegisterDeviceOK{}
}

// WithPayload adds the payload to the register device o k response
func (o *RegisterDeviceOK) WithPayload(payload *models.RegistrationConfirmation) *RegisterDeviceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register device o k response
func (o *RegisterDeviceOK) SetPayload(payload *models.RegistrationConfirmation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterDeviceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterDeviceUnauthorizedCode is the HTTP code returned for type RegisterDeviceUnauthorized
const RegisterDeviceUnauthorizedCode int = 401

/*RegisterDeviceUnauthorized Unauthorized

swagger:response registerDeviceUnauthorized
*/
type RegisterDeviceUnauthorized struct {
}

// NewRegisterDeviceUnauthorized creates RegisterDeviceUnauthorized with default headers values
func NewRegisterDeviceUnauthorized() *RegisterDeviceUnauthorized {

	return &RegisterDeviceUnauthorized{}
}

// WriteResponse to the client
func (o *RegisterDeviceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RegisterDeviceForbiddenCode is the HTTP code returned for type RegisterDeviceForbidden
const RegisterDeviceForbiddenCode int = 403

/*RegisterDeviceForbidden Forbidden

swagger:response registerDeviceForbidden
*/
type RegisterDeviceForbidden struct {
}

// NewRegisterDeviceForbidden creates RegisterDeviceForbidden with default headers values
func NewRegisterDeviceForbidden() *RegisterDeviceForbidden {

	return &RegisterDeviceForbidden{}
}

// WriteResponse to the client
func (o *RegisterDeviceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// RegisterDeviceNotFoundCode is the HTTP code returned for type RegisterDeviceNotFound
const RegisterDeviceNotFoundCode int = 404

/*RegisterDeviceNotFound Error

swagger:response registerDeviceNotFound
*/
type RegisterDeviceNotFound struct {
}

// NewRegisterDeviceNotFound creates RegisterDeviceNotFound with default headers values
func NewRegisterDeviceNotFound() *RegisterDeviceNotFound {

	return &RegisterDeviceNotFound{}
}

// WriteResponse to the client
func (o *RegisterDeviceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// RegisterDeviceInternalServerErrorCode is the HTTP code returned for type RegisterDeviceInternalServerError
const RegisterDeviceInternalServerErrorCode int = 500

/*RegisterDeviceInternalServerError Error

swagger:response registerDeviceInternalServerError
*/
type RegisterDeviceInternalServerError struct {
}

// NewRegisterDeviceInternalServerError creates RegisterDeviceInternalServerError with default headers values
func NewRegisterDeviceInternalServerError() *RegisterDeviceInternalServerError {

	return &RegisterDeviceInternalServerError{}
}

// WriteResponse to the client
func (o *RegisterDeviceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
