// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/jakub-dzon/k4e-operator/models"
)

// NewRegisterDeviceParams creates a new RegisterDeviceParams object
// no default values defined in spec.
func NewRegisterDeviceParams() RegisterDeviceParams {

	return RegisterDeviceParams{}
}

// RegisterDeviceParams contains all the bound params for the register device operation
// typically these are obtained from a http.Request
//
// swagger:parameters RegisterDevice
type RegisterDeviceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Device registration information
	  Required: true
	  In: body
	*/
	RegistrationInfo *models.RegistrationInfo
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRegisterDeviceParams() beforehand.
func (o *RegisterDeviceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RegistrationInfo
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("registrationInfo", "body", ""))
			} else {
				res = append(res, errors.NewParseError("registrationInfo", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RegistrationInfo = &body
			}
		}
	} else {
		res = append(res, errors.Required("registrationInfo", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
