// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"

	"github.com/project-flotta/flotta-operator/backend/restapi/operations"
	"github.com/project-flotta/flotta-operator/backend/restapi/operations/backend"
)

type contextKey string

const AuthKey contextKey = "Auth"

//go:generate mockery -name BackendAPI -inpkg

/* BackendAPI  */
type BackendAPI interface {
	/* EnrolDevice Initiates the process of enrolling the device */
	EnrolDevice(ctx context.Context, params backend.EnrolDeviceParams) middleware.Responder

	/* GetDeviceConfiguration Returns the device configuration */
	GetDeviceConfiguration(ctx context.Context, params backend.GetDeviceConfigurationParams) middleware.Responder

	/* GetRegistrationStatus Returns a device registration status, which can be registered, unregistered or unknown. */
	GetRegistrationStatus(ctx context.Context, params backend.GetRegistrationStatusParams) middleware.Responder

	/* GetTargetNamespace Returns target namespace for the device */
	GetTargetNamespace(ctx context.Context, params backend.GetTargetNamespaceParams) middleware.Responder

	/* RegisterDevice Registers the device by providing its hardware configuration */
	RegisterDevice(ctx context.Context, params backend.RegisterDeviceParams) middleware.Responder

	/* UpdateHeartBeat Updates the heartbeat information of the device. */
	UpdateHeartBeat(ctx context.Context, params backend.UpdateHeartBeatParams) middleware.Responder
}

// Config is configuration for Handler
type Config struct {
	BackendAPI
	Logger func(string, ...interface{})
	// InnerMiddleware is for the handler executors. These do not apply to the swagger.json document.
	// The middleware executes after routing but before authentication, binding and validation
	InnerMiddleware func(http.Handler) http.Handler

	// Authorizer is used to authorize a request after the Auth function was called using the "Auth*" functions
	// and the principal was stored in the context in the "AuthKey" context value.
	Authorizer func(*http.Request) error

	// Authenticator to use for all APIKey authentication
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// Authenticator to use for all Bearer authentication
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// Authenticator to use for all Basic authentication
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator
}

// Handler returns an http.Handler given the handler configuration
// It mounts all the business logic implementers in the right routing.
func Handler(c Config) (http.Handler, error) {
	h, _, err := HandlerAPI(c)
	return h, err
}

// HandlerAPI returns an http.Handler given the handler configuration
// and the corresponding *FlottaBackendAPI instance.
// It mounts all the business logic implementers in the right routing.
func HandlerAPI(c Config) (http.Handler, *operations.FlottaBackendAPIAPI, error) {
	spec, err := loads.Analyzed(swaggerCopy(SwaggerJSON), "")
	if err != nil {
		return nil, nil, fmt.Errorf("analyze swagger: %v", err)
	}
	api := operations.NewFlottaBackendAPIAPI(spec)
	api.ServeError = errors.ServeError
	api.Logger = c.Logger

	if c.APIKeyAuthenticator != nil {
		api.APIKeyAuthenticator = c.APIKeyAuthenticator
	}
	if c.BasicAuthenticator != nil {
		api.BasicAuthenticator = c.BasicAuthenticator
	}
	if c.BearerAuthenticator != nil {
		api.BearerAuthenticator = c.BearerAuthenticator
	}

	api.JSONConsumer = runtime.JSONConsumer()
	api.JSONProducer = runtime.JSONProducer()
	api.BackendEnrolDeviceHandler = backend.EnrolDeviceHandlerFunc(func(params backend.EnrolDeviceParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.BackendAPI.EnrolDevice(ctx, params)
	})
	api.BackendGetDeviceConfigurationHandler = backend.GetDeviceConfigurationHandlerFunc(func(params backend.GetDeviceConfigurationParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.BackendAPI.GetDeviceConfiguration(ctx, params)
	})
	api.BackendGetRegistrationStatusHandler = backend.GetRegistrationStatusHandlerFunc(func(params backend.GetRegistrationStatusParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.BackendAPI.GetRegistrationStatus(ctx, params)
	})
	api.BackendGetTargetNamespaceHandler = backend.GetTargetNamespaceHandlerFunc(func(params backend.GetTargetNamespaceParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.BackendAPI.GetTargetNamespace(ctx, params)
	})
	api.BackendRegisterDeviceHandler = backend.RegisterDeviceHandlerFunc(func(params backend.RegisterDeviceParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.BackendAPI.RegisterDevice(ctx, params)
	})
	api.BackendUpdateHeartBeatHandler = backend.UpdateHeartBeatHandlerFunc(func(params backend.UpdateHeartBeatParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.BackendAPI.UpdateHeartBeat(ctx, params)
	})
	api.ServerShutdown = func() {}
	return api.Serve(c.InnerMiddleware), api, nil
}

// swaggerCopy copies the swagger json to prevent data races in runtime
func swaggerCopy(orig json.RawMessage) json.RawMessage {
	c := make(json.RawMessage, len(orig))
	copy(c, orig)
	return c
}

// authorizer is a helper function to implement the runtime.Authorizer interface.
type authorizer func(*http.Request) error

func (a authorizer) Authorize(req *http.Request, principal interface{}) error {
	if a == nil {
		return nil
	}
	ctx := storeAuth(req.Context(), principal)
	return a(req.WithContext(ctx))
}

func storeAuth(ctx context.Context, principal interface{}) context.Context {
	return context.WithValue(ctx, AuthKey, principal)
}
