// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataPath Device-to-control plane paths mapping
//
// swagger:model dataPath
type DataPath struct {

	// Path in the workload container
	Source string `json:"source,omitempty"`

	// Path in the control plane storage
	Target string `json:"target,omitempty"`
}

// Validate validates this data path
func (m *DataPath) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this data path based on context it is used
func (m *DataPath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataPath) UnmarshalBinary(b []byte) error {
	var res DataPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
