// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	commonmodel "github.com/project-flotta/flotta-operator/models"
)

// DeviceConfigurationResponse device configuration response
//
// swagger:model device-configuration-response
type DeviceConfigurationResponse struct {

	// device configuration
	DeviceConfiguration commonmodel.DeviceConfigurationMessage `json:"device-configuration,omitempty"`

	// Exposes the error message generated at the backend when there is an error (example HTTP code 500).
	Message string `json:"message,omitempty"`
}

// Validate validates this device configuration response
func (m *DeviceConfigurationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceConfiguration(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceConfigurationResponse) validateDeviceConfiguration(formats strfmt.Registry) error {
	if swag.IsZero(m.DeviceConfiguration) { // not required
		return nil
	}

	if err := m.DeviceConfiguration.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("device-configuration")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("device-configuration")
		}
		return err
	}

	return nil
}

// ContextValidate validates this device configuration response based on context it is used
func (m *DeviceConfigurationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceConfigurationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceConfigurationResponse) UnmarshalBinary(b []byte) error {
	var res DeviceConfigurationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
