// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OsInformation OS lifecycle information
//
// swagger:model osInformation
type OsInformation struct {

	// automatically upgrade the OS image
	AutomaticallyUpgrade bool `json:"automatically_upgrade,omitempty"`

	// the last commit ID
	CommitID string `json:"commit_id,omitempty"`

	// the URL of the hosted commits web server
	HostedObjectsURL string `json:"hosted_objects_url,omitempty"`
}

// Validate validates this os information
func (m *OsInformation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this os information based on context it is used
func (m *OsInformation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OsInformation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OsInformation) UnmarshalBinary(b []byte) error {
	var res OsInformation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
