// Code generated by go-swagger; DO NOT EDIT.

package backend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDeviceConfigurationHandlerFunc turns a function with the right signature into a get device configuration handler
type GetDeviceConfigurationHandlerFunc func(GetDeviceConfigurationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDeviceConfigurationHandlerFunc) Handle(params GetDeviceConfigurationParams) middleware.Responder {
	return fn(params)
}

// GetDeviceConfigurationHandler interface for that can handle valid get device configuration params
type GetDeviceConfigurationHandler interface {
	Handle(GetDeviceConfigurationParams) middleware.Responder
}

// NewGetDeviceConfiguration creates a new http.Handler for the get device configuration operation
func NewGetDeviceConfiguration(ctx *middleware.Context, handler GetDeviceConfigurationHandler) *GetDeviceConfiguration {
	return &GetDeviceConfiguration{Context: ctx, Handler: handler}
}

/*
	GetDeviceConfiguration swagger:route GET /namespaces/{namespace}/devices/{device-id}/configuration backend getDeviceConfiguration

Returns the device configuration
*/
type GetDeviceConfiguration struct {
	Context *middleware.Context
	Handler GetDeviceConfigurationHandler
}

func (o *GetDeviceConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDeviceConfigurationParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
