// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project-flotta/flotta-operator/models"
)

// InitializeDeviceRegistrationReader is a Reader for the InitializeDeviceRegistration structure.
type InitializeDeviceRegistrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitializeDeviceRegistrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInitializeDeviceRegistrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewInitializeDeviceRegistrationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewInitializeDeviceRegistrationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewInitializeDeviceRegistrationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitializeDeviceRegistrationOK creates a InitializeDeviceRegistrationOK with default headers values
func NewInitializeDeviceRegistrationOK() *InitializeDeviceRegistrationOK {
	return &InitializeDeviceRegistrationOK{}
}

/*InitializeDeviceRegistrationOK handles this case with default header values.

Success
*/
type InitializeDeviceRegistrationOK struct {
	Payload *models.DeviceRegistrationResponse
}

func (o *InitializeDeviceRegistrationOK) Error() string {
	return fmt.Sprintf("[POST /namespaces/{namespace}/devices/{device-id}/register][%d] initializeDeviceRegistrationOK  %+v", 200, o.Payload)
}

func (o *InitializeDeviceRegistrationOK) GetPayload() *models.DeviceRegistrationResponse {
	return o.Payload
}

func (o *InitializeDeviceRegistrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceRegistrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitializeDeviceRegistrationUnauthorized creates a InitializeDeviceRegistrationUnauthorized with default headers values
func NewInitializeDeviceRegistrationUnauthorized() *InitializeDeviceRegistrationUnauthorized {
	return &InitializeDeviceRegistrationUnauthorized{}
}

/*InitializeDeviceRegistrationUnauthorized handles this case with default header values.

Unauthorized
*/
type InitializeDeviceRegistrationUnauthorized struct {
}

func (o *InitializeDeviceRegistrationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /namespaces/{namespace}/devices/{device-id}/register][%d] initializeDeviceRegistrationUnauthorized ", 401)
}

func (o *InitializeDeviceRegistrationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInitializeDeviceRegistrationForbidden creates a InitializeDeviceRegistrationForbidden with default headers values
func NewInitializeDeviceRegistrationForbidden() *InitializeDeviceRegistrationForbidden {
	return &InitializeDeviceRegistrationForbidden{}
}

/*InitializeDeviceRegistrationForbidden handles this case with default header values.

Forbidden
*/
type InitializeDeviceRegistrationForbidden struct {
}

func (o *InitializeDeviceRegistrationForbidden) Error() string {
	return fmt.Sprintf("[POST /namespaces/{namespace}/devices/{device-id}/register][%d] initializeDeviceRegistrationForbidden ", 403)
}

func (o *InitializeDeviceRegistrationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInitializeDeviceRegistrationDefault creates a InitializeDeviceRegistrationDefault with default headers values
func NewInitializeDeviceRegistrationDefault(code int) *InitializeDeviceRegistrationDefault {
	return &InitializeDeviceRegistrationDefault{
		_statusCode: code,
	}
}

/*InitializeDeviceRegistrationDefault handles this case with default header values.

Error
*/
type InitializeDeviceRegistrationDefault struct {
	_statusCode int

	Payload *models.DeviceRegistrationResponse
}

// Code gets the status code for the initialize device registration default response
func (o *InitializeDeviceRegistrationDefault) Code() int {
	return o._statusCode
}

func (o *InitializeDeviceRegistrationDefault) Error() string {
	return fmt.Sprintf("[POST /namespaces/{namespace}/devices/{device-id}/register][%d] InitializeDeviceRegistration default  %+v", o._statusCode, o.Payload)
}

func (o *InitializeDeviceRegistrationDefault) GetPayload() *models.DeviceRegistrationResponse {
	return o.Payload
}

func (o *InitializeDeviceRegistrationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceRegistrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
