// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIsDeviceDeregistrableParams creates a new IsDeviceDeregistrableParams object
// with the default values initialized.
func NewIsDeviceDeregistrableParams() *IsDeviceDeregistrableParams {
	var ()
	return &IsDeviceDeregistrableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIsDeviceDeregistrableParamsWithTimeout creates a new IsDeviceDeregistrableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIsDeviceDeregistrableParamsWithTimeout(timeout time.Duration) *IsDeviceDeregistrableParams {
	var ()
	return &IsDeviceDeregistrableParams{

		timeout: timeout,
	}
}

// NewIsDeviceDeregistrableParamsWithContext creates a new IsDeviceDeregistrableParams object
// with the default values initialized, and the ability to set a context for a request
func NewIsDeviceDeregistrableParamsWithContext(ctx context.Context) *IsDeviceDeregistrableParams {
	var ()
	return &IsDeviceDeregistrableParams{

		Context: ctx,
	}
}

// NewIsDeviceDeregistrableParamsWithHTTPClient creates a new IsDeviceDeregistrableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIsDeviceDeregistrableParamsWithHTTPClient(client *http.Client) *IsDeviceDeregistrableParams {
	var ()
	return &IsDeviceDeregistrableParams{
		HTTPClient: client,
	}
}

/*IsDeviceDeregistrableParams contains all the parameters to send to the API endpoint
for the is device deregistrable operation typically these are written to a http.Request
*/
type IsDeviceDeregistrableParams struct {

	/*DeviceID
	  Device ID

	*/
	DeviceID string
	/*Namespace
	  Namespace where the device resides

	*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) WithTimeout(timeout time.Duration) *IsDeviceDeregistrableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) WithContext(ctx context.Context) *IsDeviceDeregistrableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) WithHTTPClient(client *http.Client) *IsDeviceDeregistrableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) WithDeviceID(deviceID string) *IsDeviceDeregistrableParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithNamespace adds the namespace to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) WithNamespace(namespace string) *IsDeviceDeregistrableParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the is device deregistrable params
func (o *IsDeviceDeregistrableParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *IsDeviceDeregistrableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device-id
	if err := r.SetPathParam("device-id", o.DeviceID); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
