// Code generated by go-swagger; DO NOT EDIT.

package backend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDeviceConfigurationParams creates a new GetDeviceConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDeviceConfigurationParams() *GetDeviceConfigurationParams {
	return &GetDeviceConfigurationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeviceConfigurationParamsWithTimeout creates a new GetDeviceConfigurationParams object
// with the ability to set a timeout on a request.
func NewGetDeviceConfigurationParamsWithTimeout(timeout time.Duration) *GetDeviceConfigurationParams {
	return &GetDeviceConfigurationParams{
		timeout: timeout,
	}
}

// NewGetDeviceConfigurationParamsWithContext creates a new GetDeviceConfigurationParams object
// with the ability to set a context for a request.
func NewGetDeviceConfigurationParamsWithContext(ctx context.Context) *GetDeviceConfigurationParams {
	return &GetDeviceConfigurationParams{
		Context: ctx,
	}
}

// NewGetDeviceConfigurationParamsWithHTTPClient creates a new GetDeviceConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDeviceConfigurationParamsWithHTTPClient(client *http.Client) *GetDeviceConfigurationParams {
	return &GetDeviceConfigurationParams{
		HTTPClient: client,
	}
}

/*
GetDeviceConfigurationParams contains all the parameters to send to the API endpoint

	for the get device configuration operation.

	Typically these are written to a http.Request.
*/
type GetDeviceConfigurationParams struct {

	/* DeviceID.

	   Device ID
	*/
	DeviceID string

	/* Namespace.

	   Namespace where the device resides
	*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get device configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceConfigurationParams) WithDefaults() *GetDeviceConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get device configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get device configuration params
func (o *GetDeviceConfigurationParams) WithTimeout(timeout time.Duration) *GetDeviceConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get device configuration params
func (o *GetDeviceConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get device configuration params
func (o *GetDeviceConfigurationParams) WithContext(ctx context.Context) *GetDeviceConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get device configuration params
func (o *GetDeviceConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get device configuration params
func (o *GetDeviceConfigurationParams) WithHTTPClient(client *http.Client) *GetDeviceConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get device configuration params
func (o *GetDeviceConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the get device configuration params
func (o *GetDeviceConfigurationParams) WithDeviceID(deviceID string) *GetDeviceConfigurationParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the get device configuration params
func (o *GetDeviceConfigurationParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithNamespace adds the namespace to the get device configuration params
func (o *GetDeviceConfigurationParams) WithNamespace(namespace string) *GetDeviceConfigurationParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get device configuration params
func (o *GetDeviceConfigurationParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeviceConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device-id
	if err := r.SetPathParam("device-id", o.DeviceID); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
