// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// EnrolDeviceHandlerFunc turns a function with the right signature into a enrol device handler
type EnrolDeviceHandlerFunc func(EnrolDeviceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn EnrolDeviceHandlerFunc) Handle(params EnrolDeviceParams) middleware.Responder {
	return fn(params)
}

// EnrolDeviceHandler interface for that can handle valid enrol device params
type EnrolDeviceHandler interface {
	Handle(EnrolDeviceParams) middleware.Responder
}

// NewEnrolDevice creates a new http.Handler for the enrol device operation
func NewEnrolDevice(ctx *middleware.Context, handler EnrolDeviceHandler) *EnrolDevice {
	return &EnrolDevice{Context: ctx, Handler: handler}
}

/* EnrolDevice swagger:route POST /namespaces/{namespace}/devices/{device-id}/enrolment enrolDevice

Initiates the process of enrolling the device

*/
type EnrolDevice struct {
	Context *middleware.Context
	Handler EnrolDeviceHandler
}

func (o *EnrolDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewEnrolDeviceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
