// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/project-flotta/flotta-operator/backend/models"
)

// NewUpdateHeartBeatParams creates a new UpdateHeartBeatParams object
//
// There are no default values defined in the spec.
func NewUpdateHeartBeatParams() UpdateHeartBeatParams {

	return UpdateHeartBeatParams{}
}

// UpdateHeartBeatParams contains all the bound params for the update heart beat operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateHeartBeat
type UpdateHeartBeatParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Device ID
	  Required: true
	  In: path
	*/
	DeviceID string
	/*
	  Required: true
	  In: body
	*/
	Heartbeat models.Heartbeat
	/*Namespace where the device resides
	  Required: true
	  In: path
	*/
	Namespace string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateHeartBeatParams() beforehand.
func (o *UpdateHeartBeatParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDeviceID, rhkDeviceID, _ := route.Params.GetOK("device-id")
	if err := o.bindDeviceID(rDeviceID, rhkDeviceID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Heartbeat
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("heartbeat", "body", ""))
			} else {
				res = append(res, errors.NewParseError("heartbeat", "body", "", err))
			}
		} else {
			// no validation on generic interface
			o.Heartbeat = body
		}
	} else {
		res = append(res, errors.Required("heartbeat", "body", ""))
	}

	rNamespace, rhkNamespace, _ := route.Params.GetOK("namespace")
	if err := o.bindNamespace(rNamespace, rhkNamespace, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDeviceID binds and validates parameter DeviceID from path.
func (o *UpdateHeartBeatParams) bindDeviceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.DeviceID = raw

	return nil
}

// bindNamespace binds and validates parameter Namespace from path.
func (o *UpdateHeartBeatParams) bindNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Namespace = raw

	return nil
}
