@startuml
'https://plantuml.com/deployment-diagram
actor user

frame Kubernetes {

    node Operator {
      interface "http  API" as operatorAPI
    }

    file "EdgeWorkload CR" as workload
    file "EdgeDevice CR" as deviceCR
}

frame Device {
    component Agent
    node Podman{
      collections Workloads
    }
}

frame HostedImages {
    node WebServer{
      interface "http  API" as imageUrl
    }

    control "commit calculator \nusing rhel automation" as CommitsCalc
    collections Images
}


deviceCR o-- workload

Operator -[dashed]-> workload: process
Operator -[dashed]-> deviceCR: process

user -[#blue]-> imageUrl : (1) Add new image (2) get new commit hash
Agent ---> operatorAPI: get desired state, update status
Agent --> Podman : CRUD/monitor workloads
Agent -> imageUrl : get Image
WebServer <-> CommitsCalc

user -[#blue]-> deviceCR : update CR with new commit ID
@enduml

