@startuml
actor User
User -> HostImagesAPI  : 1) push new image
HostImagesAPI -> calculateCommit : 2) calculate new commit (using rhel automartion)
User -> HostImagesAPI  : 3) get new commit ID
User -> EdgeDeviceCR : 4) update the CR with the new commit ID
Device -> Operator : 5) get updates
Operator -> Device : 6) update include the new commit ID
Device -> Device : 7) update edge.conf file
Device -> HostImagesAPI : 8) check for the specific update
Device -> Device : 9) upgrading OS
Device -> Operator : 10) update the status using heartbeat
@enduml