{
 "title": "flotta",
 "tags": [ "flotta" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Devices management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flotta objects count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "etcd_object_counts{resource=\"edgedevices.management.project-flotta.io\"}",
       "legendFormat": "edge devices"
      },
      {
       "expr": "etcd_object_counts{resource=\"edgeworkloads.management.project-flotta.io\"}",
       "legendFormat": "edge workloads"
      }
     ]
    },
    {
     "title": "Edge devices registration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flotta_operator_edge_devices_unregistration{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", job=~\"flotta-operator-.*\"})",
       "legendFormat": "unregistered"
      },
      {
       "expr": "sum(flotta_operator_edge_devices_failed_registration{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", job=~\"flotta-operator-.*\"})",
       "legendFormat": "failed to register"
      },
      {
       "expr": "sum(flotta_operator_edge_devices_successful_registration{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", job=~\"flotta-operator-.*\"})",
       "legendFormat": "registered"
      }
     ]
    }
   ]
  },
  {
   "title": "Flotta Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 }, "options": { "content": "\n### Memory Usage\n\n\n\n" } },
    {
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\"})",
       "legendFormat": "Flotta Memory Usage"
      },
      {
       "expr": "sum(container_memory_cache{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\"})",
       "legendFormat": "Flotta Cache Usage"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 }, "options": { "content": "\n### CPU Usage\n\n\n\n" } },
    {
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "CPUs" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\"}[5m]))",
       "legendFormat": "${namespace} CPU Usage (Nb of CPUs)"
      }
     ]
    },
    {
     "type": "gauge",
     "description": "Percent of limits memory usage",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\"}) / sum(kube_pod_container_resource_limits{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\", resource=\"memory\"}) * 100",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "type": "gauge",
     "description": "Percent of limits CPU usage ",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\"}[5m])) / sum(kube_pod_container_resource_limits{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", resource=\"cpu\"}) * 100",
       "legendFormat": "Limits CPU Usage"
      },
      { "legendFormat": "Limits" }
     ]
    },
    {
     "title": "Network I/O /5min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"flotta\"}[5m]))",
       "legendFormat": "Bytes recieves"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"flotta\"}[5m]))",
       "legendFormat": "Bytes sents"
      }
     ]
    },
    {
     "title": "Network # of Errors /5min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_errors_total{namespace=\"flotta\"}[5m]))",
       "legendFormat": "Errors recives"
      },
      {
       "expr": "sum (rate (container_network_transmit_errors_total{namespace=\"flotta\"}[5m]))",
       "legendFormat": "Errors Sents"
      }
     ]
    },
    {
     "title": "Network # of Packets /(5mins)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_packets_total{namespace=\"flotta\"}[5m]))",
       "legendFormat": "Bytes recieves"
      },
      {
       "expr": "- sum (rate (container_network_transmit_packets_total{namespace=\"flotta\"}[5m]))",
       "legendFormat": "Bytes sents"
      }
     ]
    },
    {
     "title": "cpu usage, requests and limits",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
     "repeat": "podname",
     "yaxes": [
      { "format": "short", "label": "CPU" }
     ],
     "targets": [
      {
       "expr": "avg( rate(container_cpu_usage_seconds_total{namespace=\"flotta\",pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\"}[5m]))",
       "legendFormat": "Avg"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits{namespace=\"flotta\",pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"flotta\",pod=~\"flotta-operator-controller-manager-.*\", container=\"manager\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "haproxy",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_response_errors_total{exported_namespace=\"flotta\"})",
       "legendFormat": "# response errors"
      },
      {
       "expr": "sum(haproxy_server_downtime_seconds_total{exported_namespace=\"flotta\"})",
       "legendFormat": "server downtime"
      },
      {
       "expr": "sum(haproxy_backend_http_average_connect_latency_milliseconds{exported_namespace=\"flotta\"})",
       "legendFormat": "latency"
      }
     ]
    }
   ]
  }
 ]
}