// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AnsiblePlaybook ansible playbook
//
// swagger:model ansible-playbook
type AnsiblePlaybook struct {

	// Returns the ansible playbook as a string.
	AnsiblePlaybookString string `json:"ansible-playbook-string,omitempty"`
}

// Validate validates this ansible playbook
func (m *AnsiblePlaybook) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ansible playbook based on context it is used
func (m *AnsiblePlaybook) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AnsiblePlaybook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnsiblePlaybook) UnmarshalBinary(b []byte) error {
	var res AnsiblePlaybook
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
