// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ComponentMetricsConfiguration Device component's metrics gathering configuration. Used by the system (aka node-exporter) and data transfer services.
//
// swagger:model component-metrics-configuration
type ComponentMetricsConfiguration struct {

	// allow list
	AllowList *MetricsAllowList `json:"allow_list,omitempty"`

	// When true, turns metrics collection off. False by default.
	Disabled bool `json:"disabled,omitempty"`

	// Interval(in seconds) to scrape metrics endpoint.
	Interval int32 `json:"interval,omitempty"`
}

// Validate validates this component metrics configuration
func (m *ComponentMetricsConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComponentMetricsConfiguration) validateAllowList(formats strfmt.Registry) error {
	if swag.IsZero(m.AllowList) { // not required
		return nil
	}

	if m.AllowList != nil {
		if err := m.AllowList.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("allow_list")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("allow_list")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this component metrics configuration based on the context it is used
func (m *ComponentMetricsConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAllowList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComponentMetricsConfiguration) contextValidateAllowList(ctx context.Context, formats strfmt.Registry) error {

	if m.AllowList != nil {
		if err := m.AllowList.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("allow_list")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("allow_list")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComponentMetricsConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComponentMetricsConfiguration) UnmarshalBinary(b []byte) error {
	var res ComponentMetricsConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
