// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceConfiguration device configuration
//
// swagger:model device-configuration
type DeviceConfiguration struct {

	// heartbeat
	Heartbeat *HeartbeatConfiguration `json:"heartbeat,omitempty"`

	// metrics
	Metrics *MetricsConfiguration `json:"metrics,omitempty"`

	// storage
	Storage *StorageConfiguration `json:"storage,omitempty"`
}

// Validate validates this device configuration
func (m *DeviceConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHeartbeat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetrics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceConfiguration) validateHeartbeat(formats strfmt.Registry) error {

	if swag.IsZero(m.Heartbeat) { // not required
		return nil
	}

	if m.Heartbeat != nil {
		if err := m.Heartbeat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("heartbeat")
			}
			return err
		}
	}

	return nil
}

func (m *DeviceConfiguration) validateMetrics(formats strfmt.Registry) error {

	if swag.IsZero(m.Metrics) { // not required
		return nil
	}

	if m.Metrics != nil {
		if err := m.Metrics.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metrics")
			}
			return err
		}
	}

	return nil
}

func (m *DeviceConfiguration) validateStorage(formats strfmt.Registry) error {

	if swag.IsZero(m.Storage) { // not required
		return nil
	}

	if m.Storage != nil {
		if err := m.Storage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("storage")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceConfiguration) UnmarshalBinary(b []byte) error {
	var res DeviceConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
