// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceConfiguration device configuration
//
// swagger:model device-configuration
type DeviceConfiguration struct {

	// Device identifier
	DeviceID string `json:"device_id,omitempty"`

	// List of workloads deployed to the device
	Workloads WorkloadList `json:"workloads,omitempty"`
}

// Validate validates this device configuration
func (m *DeviceConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkloads(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceConfiguration) validateWorkloads(formats strfmt.Registry) error {

	if swag.IsZero(m.Workloads) { // not required
		return nil
	}

	if err := m.Workloads.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("workloads")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceConfiguration) UnmarshalBinary(b []byte) error {
	var res DeviceConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
