// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Memory memory
//
// swagger:model memory
type Memory struct {

	// physical bytes
	PhysicalBytes int64 `json:"physical_bytes,omitempty"`

	// usable bytes
	UsableBytes int64 `json:"usable_bytes,omitempty"`
}

// Validate validates this memory
func (m *Memory) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this memory based on context it is used
func (m *Memory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Memory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Memory) UnmarshalBinary(b []byte) error {
	var res Memory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
