// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsAllowList Specification of metrics to be collected
//
// swagger:model metrics-allow-list
type MetricsAllowList struct {

	// names
	Names []string `json:"names"`
}

// Validate validates this metrics allow list
func (m *MetricsAllowList) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsAllowList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsAllowList) UnmarshalBinary(b []byte) error {
	var res MetricsAllowList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
