// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsReceiverConfiguration metrics receiver configuration
//
// swagger:model metrics-receiver-configuration
type MetricsReceiverConfiguration struct {

	// request num samples
	RequestNumSamples int64 `json:"request_num_samples,omitempty"`

	// timeout seconds
	TimeoutSeconds int64 `json:"timeout_seconds,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this metrics receiver configuration
func (m *MetricsReceiverConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsReceiverConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsReceiverConfiguration) UnmarshalBinary(b []byte) error {
	var res MetricsReceiverConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
