// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsRetention metrics retention
//
// swagger:model metrics-retention
type MetricsRetention struct {

	// Maximum time in hours metrics data files should kept on the device
	MaxHours int32 `json:"max_hours,omitempty"`

	// Maximum size of metrics stored on disk
	MaxMib int32 `json:"max_mib,omitempty"`
}

// Validate validates this metrics retention
func (m *MetricsRetention) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsRetention) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsRetention) UnmarshalBinary(b []byte) error {
	var res MetricsRetention
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
