// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlaybookExecution playbook execution
//
// swagger:model playbook-execution
type PlaybookExecution struct {

	// Returns the ansible playbook as a string.
	AnsiblePlaybookString string `json:"ansible-playbook-string,omitempty"`

	// Returns the ansible playbookexecution name.
	Name string `json:"name,omitempty"`
}

// Validate validates this playbook execution
func (m *PlaybookExecution) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this playbook execution based on context it is used
func (m *PlaybookExecution) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlaybookExecution) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlaybookExecution) UnmarshalBinary(b []byte) error {
	var res PlaybookExecution
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
