// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegistrationConfirmation registration confirmation
//
// swagger:model registration-confirmation
type RegistrationConfirmation struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this registration confirmation
func (m *RegistrationConfirmation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistrationConfirmation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistrationConfirmation) UnmarshalBinary(b []byte) error {
	var res RegistrationConfirmation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
